apiVersion: cube-idp.dev/v1alpha1
kind: Cube
metadata:
  name: xxx
spec:
  cluster:
    kubernetesVersion: v1.33.1
    provider: kind
    registry: {}
  engine:
    type: flux
  gateway:
    host: cube-idp.localtest.me
    pack: traefik
    port: 8443
    ref: /Users/rafal.pieniazek/Library/CloudStorage/Dropbox/github.com/rafpe/neocube/packs/traefik
  packs:
  - ref: /Users/rafal.pieniazek/Library/CloudStorage/Dropbox/github.com/rafpe/neocube/packs/gitea
  - ref: /Users/rafal.pieniazek/Library/CloudStorage/Dropbox/github.com/rafpe/neocube/packs/argocd
